steps:
  - label: ":docker: Build $BUILDKITE_PIPELINE_SLUG image"
    command: .buildkite/bin/build

  - wait

  - label: ":inspec: InSpec"
    command: .buildkite/bin/test
    plugins:
      - docker#v3.8.0:
          image: $BUILDKITE_ORGANIZATION_SLUG/$BUILDKITE_PIPELINE_SLUG:rc
          propagate-environment: true

  - label: ":git: Dry Run"
    commands:
      - "echo '+++ :git: semantic-release'"
      - semantic-release --dry-run
    plugins:
      - docker#v3.8.0:
          image: $BUILDKITE_ORGANIZATION_SLUG/$BUILDKITE_PIPELINE_SLUG:rc
          mount-ssh-agent: true
          propagate-environment: true
          environment:
            - GITHUB_TOKEN

  - wait

  - label: ":docker: Tag release"
    command: .buildkite/bin/release
    branches: master